version: '3.8'

volumes:
  pg-data:
    driver: local
  static:

services:
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5434:5432

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - 80:80
    depends_on:
      - app

  app:
    <<: &app
      depends_on:
        - db
      build:
        context: .
        dockerfile: ./Dockerfile
      env_file:
        - .env
      volumes:
        - .:/code
        - static:/static
      environment:
        POSTGRES_HOST: db
        DJANGO_SETTINGS_MODULE: petme.settings.development
    ports:
      - 8000:8000
    command: gunicorn -b 0.0.0.0:8000 -w 4 petme.wsgi:application

