# Generated by Django 3.1.1 on 2021-07-22 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название породы')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип окраса, например: Серый, Черный, Пятнистый')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfPet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип животного, например: Кошка, Собака, Птица')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moniker', models.CharField(max_length=200, verbose_name='Кличка животного')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фотография животного')),
                ('sex', models.CharField(choices=[('male', 'm'), ('female', 'f')], max_length=15, verbose_name='Пол питомца')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets_breed', to='pets.breed')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets_color', to='pets.color')),
            ],
        ),
        migrations.AddField(
            model_name='breed',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_breeds', to='pets.typeofpet'),
        ),
    ]
