# Generated by Django 3.1.1 on 2021-07-23 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'verbose_name': 'Порода животного', 'verbose_name_plural': 'Породы животных'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Окрас животного', 'verbose_name_plural': 'Окрасы животных'},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Питомец', 'verbose_name_plural': 'Питомцы'},
        ),
        migrations.AlterModelOptions(
            name='typeofpet',
            options={'verbose_name': 'Тип животного', 'verbose_name_plural': 'Типы животных'},
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=200)),
                ('second_name', models.TextField(max_length=200)),
                ('third_name', models.TextField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_users', to='pets.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pets', to='pets.profile')),
            ],
            options={
                'verbose_name': 'Принадлежность питомцев и пользователей',
                'verbose_name_plural': 'Принадлежность питомцев и пользователей',
            },
        ),
    ]
